name: "Build & Deploy Docker Image"

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Container
      run: |
        docker login -u  ${{ secrets.REGISTRY_SNICEIO_USER }} -p ${{ REGISTRY_SNICEIO_SECRET }} registry.snice.io
        make build push
